import { ExternalLink, Download, ChevronLeft } from "lucide-react";
import type { Report } from "@/types";
import { useAppStore } from "@/store/useAppStore";
import { IconButton } from "@/components/common/IconButton";

interface ReportViewerProps {
  report: Report;
}

export function ReportViewer({ report }: ReportViewerProps) {
  function handleBack() {
    useAppStore.setState((s) => ({
      workspace: { ...s.workspace, selectedReportId: null },
    }));
  }

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center gap-1 border-b border-border px-2 py-2 shrink-0">
        <IconButton
          icon={ChevronLeft}
          label="Back to report list"
          onClick={handleBack}
        />
        <p className="flex-1 truncate text-sm font-medium pl-1">{report.title}</p>
        <IconButton
          icon={ExternalLink}
          label="Open report in new tab"
          onClick={() => window.open(report.url, "_blank", "noopener,noreferrer")}
        />
        <a href={report.url} download={report.filename} tabIndex={-1}>
          <IconButton icon={Download} label="Download report" />
        </a>
      </div>

      {/*
        TICKET-013: sandbox is allow-same-origin allow-popups only.

        allow-scripts is intentionally ABSENT. HTML reports generated by
        report_generate_html are static Jinja2 documents that embed charts
        as base64 <img> tags — they require no script execution to render.

        allow-same-origin is safe here because allow-scripts is absent:
        without scripts, same-origin access cannot be exploited to reach
        the parent frame.

        NEVER add allow-scripts to this iframe without re-evaluating XSS
        risk from user-supplied data that flows into report section content.
      */}
      <div className="flex-1 min-h-0 p-3">
        <iframe
          src={report.url}
          title={report.title}
          sandbox="allow-same-origin allow-popups"
          className="h-full w-full rounded-md bg-white border border-border/50"
        />
      </div>
    </div>
  );
}
